image:
  repository: "582604091743.dkr.ecr.ap-southeast-1.amazonaws.com/inventory-service"
  tag: "main-dafcfe1"
service:
  port: 8083
serviceAccount:
  create: true
  annotations:
    eks.amazonaws.com/role-arn: "arn:aws:iam::582604091743:role/ecommerce-inventory-service-role"
env:
  - name: SERVER_PORT
    value: "8083"
  - name: SPRING_DATASOURCE_URL
    value: "jdbc:postgresql://ecommerce-inventory-service-db-prod.xxxx.ap-southeast-1.rds.amazonaws.com:5432/inventorydb"
  - name: SPRING_DATASOURCE_USERNAME
    valueFrom:
      secretKeyRef:
        name: ecommerce-db-credentials
        key: username
  - name: SPRING_DATASOURCE_PASSWORD
    valueFrom:
      secretKeyRef:
        name: ecommerce-db-credentials
        key: password
  - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
    value: "b-1.ecommerce-msk.xxxx.kafka.ap-southeast-1.amazonaws.com:9092,b-2.xxxx:9092"
  - name: SPRING_PROFILES_ACTIVE
    value: "prod"
autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 70
