# values/order-service.yaml
image:
  repository: 123456789012.dkr.ecr.us-east-1.amazonaws.com/order-service
  tag: latest

service:
  port: 8081

env:
  - name: SPRING_DATASOURCE_URL
    value: "jdbc:postgresql://ecommerce-db.xxxx.us-east-1.rds.amazonaws.com:5432/order_db"
  - name: SPRING_DATASOURCE_USERNAME
    value: "order_user"
  - name: SPRING_DATASOURCE_PASSWORD
    value: "secret"
  - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
    value: "msk-bootstrap:9092"
  - name: SERVER_PORT
    value: "8081"

ingress:
  enabled: true
  hosts:
    - host: order.ecommerce.com
      paths:
        - path: /
          pathType: Prefix

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 10
