image:
  repository: "582604091743.dkr.ecr.ap-southeast-1.amazonaws.com/user-service"
  tag: "main-a1b2c3d"

service:
  port: 8081

serviceAccount:
  create: true
  annotations:
    eks.amazonaws.com/role-arn: "arn:aws:iam::582604091743:role/ecommerce-user-service-role"

env:
  - name: SERVER_PORT
    value: "8081"
  - name: SPRING_DATASOURCE_URL
    value: "jdbc:postgresql://ecommerce-user-service-db-prod.xxxx.ap-southeast-1.rds.amazonaws.com:5432/userdb"
  - name: SPRING_DATASOURCE_USERNAME
    valueFrom:
      secretKeyRef:
        name: ecommerce-db-credentials
        key: username
  - name: SPRING_DATASOURCE_PASSWORD
    valueFrom:
      secretKeyRef:
        name: ecommerce-db-credentials
        key: password
  - name: JWT_SECRET
    valueFrom:
      secretKeyRef:
        name: ecommerce-jwt-secret
        key: jwt_secret
  - name: SPRING_PROFILES_ACTIVE
    value: "prod"

ingress:
  enabled: true
  hosts:
    - host: user.ecommerce.example.com
      paths:
        - path: /
          pathType: Prefix

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 8
  targetCPUUtilizationPercentage: 70
