{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "microservice.serviceAccountName" . }}
  labels:
    {{- include "microservice.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    # IRSA ANNOTATION — This is the key to giving pods AWS permissions
    # When this ServiceAccount is used by a pod, EKS automatically injects
    # temporary AWS credentials for the specified IAM role.

    # Set in values/<service>.yaml:
    #   serviceAccount:
    #     annotations:
    #       eks.amazonaws.com/role-arn: arn:aws:iam::123456789012:role/ecommerce-order-service-role
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
